/* itasks-v1.js
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Copyright © 2023-2024 Kris Coolsaet (Universiteit Gent)
 *
 * This software is distributed under the MIT License - see files LICENSE and AUTHORS
 * in the top level project directory.
 */

/* Simplifies communication between task page in an internal frame and the encloding
   page generated by the Bebras system.

   Clients must provide the following functions:

   initializeTask(answerAsString,modelAsString) - called when the task is first loaded
   getAnswerString() - returns the answer as a string to be stored in the database, this string cannot contain a colon (':')
   getModelString() - returns the page model as a string to be stored in the database
 */

respondToITaskMessage = function (e) {
    // e.data is the string sent by the origin with postMessage.
    if (e.data === 'getAnswer') {
        e.source.postMessage('answer:' + getAnswerString(), e.origin);
    } else if (e.data === 'getModel') {
        e.source.postMessage('model:' + getModelString(), e.origin);
    } else if (e.data.startsWith('init:')) {
        const data = e.data.split(':');
        const answerAsString = data[1];
        const modelAsString = data.slice(2).join(':');
        initializeTask(answerAsString, modelAsString);
    }
}

window.addEventListener('message', respondToITaskMessage, false);


