/* itasks-v1.js
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Copyright © 2023-2024 Kris Coolsaet (Universiteit Gent)
 *
 * This software is distributed under the MIT License - see files LICENSE and AUTHORS
 * in the top level project directory.
 */

/* Simplifies communication between task page in an internal frame and the encloding
   page generated by the Bebras system.

   Clients must provide the following functions:

   initializeTask(userid,taskid,answerAsString) - called when the task is first loaded
   getAnswerString() - returns the answer as a string to be stored in the database
 */

respondToITaskMessage = function (e) {
    // e.data is the string sent by the origin with postMessage.
    if (e.data === 'getAnswer') {
        e.source.postMessage('answer:' + getAnswerString(), e.origin);
    } else if (e.data.startsWith('init:')) {
        const data = e.data.split(':');
        const userid = data[1];
        const taskid = data[2];
        const answerAsString = data.slice(3).join(':');
        initializeTask(userid, taskid, answerAsString);
    }
}

window.addEventListener('message', respondToITaskMessage, false);

/* Initializes local storage for this contest. Cleans up data which does
   not belong to the current user.
 */
function initializeLocalStorage(userid) {
    const storedUserid = localstorage.getItem('userid');
    if (storedUserid !== null && storedUserid !== userid) {
        // clean up data from previous user
        localStorage.clear();
    }
    localStorage.setItem('userid', userid);
}


