--  classes.sql
--  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--  Copyright © 2023-2024 Kris Coolsaet (Universiteit Gent)
--
--  This software is distributed under the MIT License - see files LICENSE and AUTHORS
--  in the top level project directory.

-- schools
----------

CREATE TABLE schools
(
    school_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_name   TEXT NOT NULL,
    school_street TEXT,
    school_zip    TEXT,
    school_town   TEXT,

    when_created  TIMESTAMP DEFAULT NOW(),
    who_created   INTEGER,
    when_updated  TIMESTAMP,
    who_updated   INTEGER
);

CREATE TRIGGER update_school
    BEFORE UPDATE
    ON schools
    FOR EACH ROW EXECUTE PROCEDURE update_when_modified();

-- years
---------

CREATE TABLE years
(
    year_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            -- ids are expected to be in chronological order
    year_name    TEXT NOT NULL,

    when_created TIMESTAMP DEFAULT NOW(),
    who_created  INTEGER,
    when_updated TIMESTAMP,
    who_updated  INTEGER
);

CREATE TRIGGER update_year
    BEFORE UPDATE
    ON years
    FOR EACH ROW EXECUTE PROCEDURE update_when_modified();

-- classes
----------

CREATE TABLE classes
(
    class_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id    INTEGER REFERENCES schools, -- school to which this class belongs
    year_id      INTEGER REFERENCES years,   -- year to which this class belongs
    class_name   TEXT NOT NULL,

    when_created TIMESTAMP DEFAULT NOW(),
    who_created  INTEGER,
    when_updated TIMESTAMP,
    who_updated  INTEGER,
    UNIQUE (school_id, year_id, class_name)
);

CREATE TRIGGER update_class
    BEFORE UPDATE
    ON classes
    FOR EACH ROW EXECUTE PROCEDURE update_when_modified();
