--  events.sql
--  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--  Copyright © 2023-2024 Kris Coolsaet (Universiteit Gent)
--
--  This software is distributed under the MIT License - see files LICENSE and AUTHORS
--  in the top level project directory.

-- if the record exists, then permission is granted to the given user to
-- participate in the local contest

CREATE TYPE event_status AS ENUM ('PENDING', 'OPEN', 'CLOSED');

CREATE TABLE events
(
    event_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_status event_status NOT NULL DEFAULT 'PENDING',
    contest_id   INTEGER, -- references contests
    age_group_id INTEGER,
    school_id    INTEGER REFERENCES schools,
    year_id      INTEGER REFERENCES years,
    lang         TEXT,
    event_title  TEXT,

    when_created TIMESTAMP             DEFAULT NOW(),
    who_created  INTEGER,
    when_updated TIMESTAMP,
    who_updated  INTEGER,

    FOREIGN KEY (contest_id, age_group_id) REFERENCES contests_ag,
    FOREIGN KEY (contest_id, lang) REFERENCES contests_i18n
);

CREATE TRIGGER update_event
    BEFORE UPDATE
    ON events
    FOR EACH ROW
EXECUTE PROCEDURE update_when_modified();

CREATE TABLE permissions
(
    event_id     INTEGER REFERENCES events,
    pupil_id     INTEGER REFERENCES pupils,

    when_created TIMESTAMP DEFAULT NOW(),
    who_created  INTEGER,
    when_updated TIMESTAMP,
    who_updated  INTEGER,

    PRIMARY KEY (event_id, pupil_id)
);

CREATE TRIGGER update_permission
    BEFORE UPDATE
    ON permissions
    FOR EACH ROW
EXECUTE PROCEDURE update_when_modified();

-- grant permission to an entire class
--
-- parameters: event_id, class_id, who_created
CREATE OR REPLACE PROCEDURE grant_permission_to_class(INTEGER, INTEGER, INTEGER) AS
$$
DECLARE
    id INTEGER;
BEGIN
    FOR id IN
        SELECT pupil_id
        FROM classes
                 JOIN pupils_classes USING (class_id)
                 JOIN events USING (school_id)
        WHERE class_id = $2 AND event_id = $1
        LOOP
            INSERT INTO permissions(event_id, pupil_id, who_created)
            VALUES ($1, id, $3)
            ON CONFLICT(event_id, pupil_id) DO NOTHING;
        END LOOP;
END
$$ LANGUAGE 'plpgsql';

